const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0ZFUVpMdFEySlovM0N1cjVBcVZyWHRXaTRmUUNkRjJ3ZzNMYUlOWXlFYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVJvZEwwSlBpSHV4SDdzWVZnaFVDcit6am1UY1VQZ2N4MWM1dm1HcW4xST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzSFBTY0Nxa3p6RkR5UG9wWjFHOUZPRFc5TzhRMU1sUlZQdi9PU2VsSVZJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXcjR5T1E3ejg4QzZVeWxmYlNkb09jWUpxc2JJYldLOVZCOHpqaDNWUGdBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklDZWNNeTQ0NHFlUERjTWxJbi81L3VsRzVmYlIvM0tMa2dnN0JsaDB5RTQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFrQXAwb1MrcFBVM1V0OFFBdm9ZcWxNMGJleGJZY3I3M1J5ZHk1NnRNeG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUx4WGFyTENvVjNpTC9RbDBpQ3FqYlVXdXFCVXdTSFhuYVU4enBTbi9FUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOXdneHJPcFRocVZESmFnNjFXcnQ1WFd5Q1N6aXF5aFAwOGtYeHJ2RHRTQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlJTTVhMVnE0dDNrajlhZ1BNU1R6cmxOazBNT2JJdFRjN21ycVZ3Q1MzV1U0bktRWjBFaXVzREhUeEhUalBvczZ3b1BRZUpuY3RNUnlZRVBZWjlNekRBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MSwiYWR2U2VjcmV0S2V5IjoiQWQvSjJucWF6ZXdVbUE0ZVlvRUFSZ1htcHF0QzlzTmdFTlpMaWRJT3c1az0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoieW4wWmFTMElTS21RMm1ia2tpWkdYdyIsInBob25lSWQiOiI0YWY2YzY0Yy1jZWY0LTRlYTYtYjJmNS1kYjk4Yzc3OGM2YzUiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZEViOHRvVzZONXhFSzltTldJaExDN3pzUmJZPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmMnpjUUw0Z0s4QUxnZ0V0VUxQNS85dWJ6YTA9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNOS0R4SmdERUtQQjJic0dHQVVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ0YVBQL0gzMm94OGx2RzQ5eExoVi81M1AzRSs2ZXVEYUtqTHFvL3ZtUm1jPSIsImFjY291bnRTaWduYXR1cmUiOiJhV01wVFZEYVFKaDdZaEI2L0hhVi9FcWpUMEpieU45QmczSHdpcGVkUE9Dem9pSlU2V1BtL1ZlajVoMlc1VS9jWEhTR0VXVmNBVDg1V2JCSVZGbjdDQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoibGV2RUpuQUlPRVVQWTNIMzVhUUdZcXFzaDhZcEcrelczTU1ybkMrbDdLYkQ0VHhRTjN4OFJPeC9jemYwMzVjcjM0QVp1dUxUWTRBWVh2dlozOWpDQ3c9PSJ9LCJtZSI6eyJpZCI6IjIzMzUzNjM5NDM0OToxMkBzLndoYXRzYXBwLm5ldCJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzM1MzYzOTQzNDk6MTJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYldqei94OTlxTWZKYnh1UGNTNFZmK2R6OXhQdW5yZzJpb3k2cVA3NWtabiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTgxMTI0OSwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBYUkifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "+233536394349",
  "OWNER_NAME": process.env.OWNER_NAME || "Mike",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
